=== hmcts/cpp-context-sjp/sjp-json/src/main/resources/json/schema/fragments/listing-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/listing-details.json",
  "type": "object",
  "properties": {
    "referralReasonId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "hearingTypeId": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "estimatedHearingDuration": {
      "type": "integer",
      "minimum": 1,
      "maximum": 999
    },
    "listingNotes": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/note.json"
    },
    "requestedAt": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/date-time"
    }
  },
  "required": [
    "referralReasonId",
    "hearingTypeId",
    "estimatedHearingDuration",
    "requestedAt"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-sjp/sjp-json/src/main/resources/json/example/fragments/listing-details.json
{
  "referralReasonId": "8cda35cc-8073-41d7-a160-609bfe362f47",
  "hearingTypeId": "1b5fbb45-fe56-4405-ac53-d13802394150",
  "estimatedHearingDuration": 30,
  "requestedAt": "2018-06-01T09:00:00Z",
  "listingNotes": {
    "id": "7dfcf915-adb2-4ce0-9a81-bf45072f7bac",
    "text": "test note",
    "type": "DECISION",
    "addedAt": "2018-06-01T09:00:00.000Z"
  }
}
