=== hmcts/cpp-context-sjp/sjp-event/sjp-event-processor/src/raml/json/schema/public.sjp.financial-means-updated.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/public/events/financial-means-udpated.json",
  "type": "object",
  "properties": {
    "defendantId": {
      "$ref": "http://justice.gov.uk/json/schemas/core/data-types.json#/definitions/uuid"
    },
    "income": {
      "type": "object",
      "properties": {
        "frequency": {
          "enum": [
            "WEEKLY",
            "MONTHLY",
            "FORTNIGHTLY",
            "YEARLY"
          ]
        },
        "amount": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "benefits": {
      "type": "object",
      "properties": {
        "claimed": {
          "type": "boolean"
        },
        "type": {
          "type": "string"
        },
        "deductPenaltyPreference": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "employmentStatus": {
      "type": "string"
    },
    "outgoings": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "amount": {
            "type": "number"
          }
        },
        "additionalProperties": false
      }
    },
    "updatedByOnlinePlea": {
      "type": "boolean"
    },
    "updatedDate": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#date-time"
    }
  },
  "required": [
    "defendantId",
    "income",
    "benefits"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-sjp/sjp-event/sjp-event-processor/src/raml/json/public.structure.financial-means-updated.json
{
  "defendantId": "50770ba9-37ea-4713-8cab-fe5bf1202716",
  "income": {
    "amount": 100.1,
    "frequency": "MONTHLY"
  },
  "benefits": {
    "claimed": true,
    "type": "free text describing benefits type",
    "deductPenaltyPreference": false
  },
  "employmentStatus": "EMPLOYED",
  "outgoings": [
    {
      "description": "Accommodation",
      "amount": 50
    },
    {
      "description": "Council Tax",
      "amount": 50
    }
  ]
}
