=== hmcts/cpp-context-sjp/sjp-event/sjp-event-processor/src/raml/json/schema/structure.events.sjp-case-created.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    }
  },
  "type": "object",
  "properties": {
    "urn": {
      "id": "/urn",
      "type": "string"
    },
    "id": {
      "$ref": "#/definitions/uuid",
      "type": "string"
    },
    "ptiUrn": {
      "id": "/ptiUrn",
      "type": "string"
    },
    "initiationCode": {
      "id": "/initiationCode",
      "type": "string"
    },
    "summonsCode": {
      "id": "/summonsCode",
      "type": "string"
    },
    "prosecutingAuthority": {
      "id": "/prosecutingAuthority",
      "type": "string",
      "enum": [
        "TFL"
      ]
    },
    "libraOriginatingOrg": {
      "id": "/libraOriginatingOrg",
      "type": "string"
    },
    "libraHearingLocation": {
      "id": "/libraHearingLocation",
      "type": "string"
    },
    "dateOfHearing": {
      "id": "/dateOfHearing",
      "type": "string"
    },
    "timeOfHearing": {
      "id": "/timeOfHearing",
      "type": "string"
    },
    "personId": {
      "id": "/personId",
      "type": "string"
    },
    "defendantId": {
      "id": "/defendantId",
      "type": "string"
    },
    "numPreviousConvictions": {
      "id": "/numPreviousConvictions",
      "type": "integer"
    },
    "costs": {
      "id": "/costs",
      "type": "number"
    },
    "postingDate": {
      "id": "/postingDate",
      "type": "string"
    },
    "offences": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "prosecutorCaseId": {
            "type": "string"
          },
          "offenceSequenceNo": {
            "type": "integer"
          },
          "libraOffenceCode": {
            "type": "string"
          },
          "chargeDate": {
            "type": "string"
          },
          "libraOffenceDateCode": {
            "type": "integer"
          },
          "offenceDate": {
            "type": "string"
          },
          "offenceWording": {
            "type": "string"
          },
          "prosecutionFacts": {
            "type": "string"
          },
          "witnessStatement": {
            "type": "string"
          },
          "compensation": {
            "id": "/compensation",
            "type": "number"
          }
        },
        "required" : [
          "prosecutorCaseId",
          "offenceSequenceNo",
          "libraOffenceCode",
          "chargeDate",
          "libraOffenceDateCode",
          "offenceDate",
          "offenceWording"
        ]
      }
    }
  },
  "required": [
    "urn",
    "id",
    "ptiUrn",
    "initiationCode",
    "summonsCode",
    "prosecutingAuthority",
    "libraOriginatingOrg",
    "dateOfHearing",
    "timeOfHearing",
    "personId",
    "defendantId"
  ]
}

=== hmcts/cpp-context-sjp/sjp-event/sjp-event-listener/src/raml/json/sjp.events.sjp-case-created.json
{
  "id": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "urn": "22C22222222",
  "ptiUrn": "22C22222222",
  "initiationCode": "J",
  "summonsCode": "M",
  "prosecutingAuthority": "TFL",
  "libraOriginatingOrg": "GAFTL00",
  "libraHearingLocation": "B01CE03",
  "dateOfHearing": "2016-01-01",
  "timeOfHearing": "11:00",
  "personId": "7e2f843e-d639-40b3-8611-8015f3a18999",
  "defendantId": "4f37f1a1-aa76-4d53-8cc3-b2ef49f0d8a4",
  "numPreviousConvictions": 2,
  "costs": 1.23,
  "postingDate": "2015-12-02",
  "offences": [
    {
      "id": "7e2f843e-d639-40b3-8611-8015f3a18954",
      "prosecutorCaseId": "TFL21345",
      "offenceSequenceNo": 1,
      "libraOffenceCode": "PS00001",
      "chargeDate": "2016-01-01",
      "libraOffenceDateCode": 1,
      "offenceDate": "2016-01-01",
      "offenceWording": "Committed some offence",
      "prosecutionFacts": "No ticket at the gates, forgery",
      "witnessStatement": "Jumped over the barriers",
      "compensation": 2.34
    }
  ]
}
