=== hmcts/cpp-context-sjp/sjp-query/sjp-query-api/src/raml/json/schema/sjp.query.enriched-case-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/queries/enriched-case-details.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "urn": {
      "type": "string"
    },
    "defendant": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/queries/enriched-defendant.json"
    },
    "dateTimeCreated": {
      "type": "string"
    },
    "caseDocuments": {
      "type": "array",
      "items": {
        "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/queries/document.json"
      }
    },
    "prosecutingAuthority": {
      "type" : "string"
    },
    "prosecutingAuthorityName": {
      "type" : "string"
    },
    "completed": {
      "type": "boolean"
    },
    "assigned": {
      "type": "boolean"
    },
    "costs": {
      "type": "number"
    },
    "postingDate": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date"
    },
    "adjournedTo": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date"
    },
    "reopenedDate": {
      "type": "string"
    },
    "libraCaseNumber": {
      "type": "string"
    },
    "reopenedInLibraReason": {
      "type": "string"
    },
    "enterpriseId": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/enterprise-id.json"
    },
    "onlinePleaReceived": {
      "type" : "boolean"
    },
    "datesToAvoid": {
      "type" : "string"
    },
    "status": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/case-status.json"
    },
    "listedInCriminalCourts": {
      "type": "boolean"
    }
  },
  "additionalProperties": true,
  "required": [
    "id",
    "urn"
  ]
}

=== hmcts/cpp-context-sjp/sjp-query/sjp-query-api/src/raml/json/sjp.query.enriched-case-details.json
{
  "assigned": false,
  "caseDocuments": [],
  "completed": false,
  "costs": 12.0,
  "dateTimeCreated": "2019-03-08T14:34:09.054Z",
  "defendant": {
    "caseId": "3dd22595-76bc-4045-8b06-3d037d32930f",
    "id": "335322e5-c2de-45f0-b54a-3ff59c0f33d0",
    "interpreter": {
      "needed": false
    },
    "numPreviousConvictions": 2,
    "offences": [
      {
        "chargeDate": "2019-02-01",
        "cjsCode": "CA03013",
        "compensation": 10.0,
        "id": "ea6b810f-81b4-4dcd-ac6f-7a83565f744b",
        "offenceCode": "CA03013",
        "offenceSequenceNumber": 1,
        "prosecutionFacts": "On 01/11/2017 at Chelmsford, the defendant intentionally obstructed a person authorised by BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017",
        "sequenceNumber": 1,
        "startDate": "2019-01-01",
        "wording": "On 01/11/2017 at Chelmsford intentionally obstructed a person authorised by the BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017 ",
        "wordingWelsh": "On 01/11/2017 at Chelmsford intentionally obstructed a person authorised by the BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017 ",
        "title": "Possess / control TV set with intent another use install without a licence",
        "legislation": "Contrary to section 363(3)(b) and (4) of the Communications Act 2003."
      },
      {
        "chargeDate": "2019-02-04",
        "cjsCode": "WM85118",
        "compensation": 30.0,
        "id": "5d1060ae-1abd-465b-9b52-a6deb1706919",
        "offenceCode": "WM85118",
        "offenceSequenceNumber": 2,
        "prosecutionFacts": "On 01/11/2017 at Chelmsford, the defendant intentionally obstructed a person authorised by BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017",
        "sequenceNumber": 2,
        "startDate": "2019-01-01",
        "wording": "On 01/11/2017 at Chelmsford intentionally obstructed a person authorised by the BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017 ",
        "wordingWelsh": "On 01/11/2017 at Chelmsford intentionally obstructed a person authorised by the BBC in the exercise of a power conferred by virtue of a search warrant issued under section 366 of the Communications Act 2003 by Chelmsford Magistrates Court on 25/10/2017 ",
        "title": "Weights and measures inspector stamp equipment in contravention of Act / regulation / instrument",
        "titleWelsh": "Arolygydd pwysau a mesurau'n stampio cyfarpar yn groes i Ddeddf / rheoliad / offeryn",
        "legislation": "Contrary to sections 75(1)(a) and 84(6) of the Weights and Measures Act 1985",
        "legislationWelsh": "Yn groes i adrannau 75(1)(a) a 84(6) Deddf Pwysau a Mesurau 1985"
      },
      {
        "chargeDate": "2019-02-04",
        "cjsCode": "RT88461",
        "compensation": 10.0,
        "id": "5d1060ae-1abd-465b-9b52-a6deb1706919",
        "offenceCode": "RT88461",
        "offenceSequenceNumber": 3,
        "prosecutionFacts": "On 01/11/2017 at Chelmsford, the defendant rode a pedal cycle on a road and failed to stop when directed by a uniformed police constable",
        "sequenceNumber": 3,
        "startDate": "2019-01-01",
        "wording": "On 01/11/2017 at Chelmsford, being the rider of a cycle on a road, failed to stop on being required to do so",
        "wordingWelsh": "On 01/11/2017 at Chelmsford, being the rider of a cycle on a road, failed to stop on being required to do so",
        "title": "Ride a pedal cycle on a road and fail to stop when directed by a uniformed police constable / traffic warden",
        "legislation": "Contrary to section 163(3) of the Road Traffic Act 1988 and Schedule 2 to the Road Traffic Offenders Act 1988.",
        "legislationWelsh": "Yn groes i adran 163(3) Deddf Traffig Ffyrdd 1988 ac Atodlen 2 Deddf Troseddwyr Traffig Ffyrdd 1988."
      }
    ],
    "personalDetails": {
      "address": {
        "address1": "Flat 1, Armageddon House",
        "address2": "13 Old Road",
        "address3": "Giggleswick",
        "address4": "Merton",
        "address5": "London",
        "postcode": "DN35 1AB"
      },
      "addressChanged": false,
      "contactDetails": {
        "email": "email_primary@ghijkl.com",
        "home": "02099999999",
        "mobile": "0754321007"
      },
      "dateOfBirth": "1968-03-20",
      "dobChanged": false,
      "firstName": "Brock Brock Brock",
      "gender": "Male",
      "lastName": "Smith",
      "nameChanged": false,
      "nationalInsuranceNumber": "AE123456C",
      "title": "Mr"
    }
  },
  "enterpriseId": "RSHFYMTTMFKD",
  "id": "3dd22595-76bc-4045-8b06-3d037d32930f",
  "listedInCriminalCourts": false,
  "onlinePleaReceived": false,
  "postingDate": "2019-02-08",
  "prosecutingAuthority": "TVL",
  "status": "NO_PLEA_RECEIVED_READY_FOR_DECISION",
  "urn": "TVL556477M6P6"
}

=== hmcts/cpp-context-sjp/sjp-query/sjp-query-view/src/test/resources/data/sjp.query.case.json
{
  "id": "5c019f8a-b3a3-40e5-9709-c54bc4f1c55c",
  "urn": "TFL75947ZQ8UE",
  "defendant": {
    "id": "c4d922ba-20c6-4d68-ab56-3611401bbc7c",
    "offences": [
      {
        "id": "b511eb31-c8e7-4223-8626-958c34dfb3f9",
        "offenceCode": "PS90010",
        "offenceSequenceNumber": 1,
        "wording": "On 02/07/2015 At Threadneedle Street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without a Conductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction ",
        "wordingWelsh": "Welsh wording: On 02/07/2015 At Threadneedle Street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without a Conductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction ",
        "cjsCode": "PS90010",
        "sequenceNumber": 1,
        "startDate": "2017-12-29",
        "chargeDate": "2018-01-03",
        "compensation": 10,
        "prosecutionFacts": "An incident took place at GREEN PARK station whereby you were spoken to by a member of London Underground staff regarding your train journey and the associated fare.The facts of this incidents are now being considered and I must advise you that legal proceedings may be initiated against you regarding this matter in accordance with the LU prosecution policy"
      },
      {
        "id": "68dc17b3-e783-4c33-bd31-f84dc467b60f",
        "offenceCode": "PS90011",
        "plea": "GUILTY",
        "offenceSequenceNumber": 2,
        "chargeDate": "2016-02-18",
        "wording": "On 19/01/2016 At wandsworth bridge rd SW6 Being a passenger on a Public Service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares did use in relation to the journey you were taking a ticket which had been issued for use by another person on terms that it is not transferable",
        "pendingWithdrawal": false
      },
      {
        "id": "c6e95db8-b9a7-4aff-89d4-4aba39bd8300",
        "offenceCode": "PS90015",
        "plea": "GUILTY",
        "pleaMethod": "ONLINE",
        "offenceSequenceNumber": 3,
        "chargeDate": "2016-02-18",
        "wording": "On 19/01/2016 At wandsworth bridge rd SW6 Being a passenger on a Public Service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares did use in relation to the journey you were taking a ticket which had been issued for use by another person on terms that it is not transferable",
        "pendingWithdrawal": false
      }
    ],
    "caseId": "5c019f8a-b3a3-40e5-9709-c54bc4f1c55c",
    "interpreter": {
      "needed": false
    },
    "numPreviousConvictions": 2,
    "personalDetails": {
      "title": "Mr",
      "firstName": "John",
      "lastName": "Smith",
      "dateOfBirth": "1965-12-27",
      "gender": "Male",
      "nationalInsuranceNumber": "QQ 12 34 56 C",
      "address": {
        "address1": "Flat 1",
        "address2": "Armageddon House",
        "address3": "Giggleswick",
        "address4": "Merton",
        "address5": "Greater London",
        "postcode": "L32 1AB"
      },
      "contactDetails": {
        "home": "020 7219 5206",
        "mobile": "020 7219 5207",
        "email": "test@test.com"
      }
    }
  },
  "dateTimeCreated": "2018-02-02T12:51:58.742Z",
  "caseDocuments": [
    {
      "id": "7bde207f-ce57-49e5-b961-7577831171fb",
      "materialId": "7bde207f-ce57-49e5-b961-7577831171fb",
      "documentType": "SJPN",
      "documentNumber": 1,
      "addedAt": "2018-08-26T14:55:47.631Z"
    }
  ],
  "prosecutingAuthority": "DVLA",
  "completed": false,
  "assigned": false,
  "costs": 20,
  "postingDate": "2018-01-05",
  "enterpriseId": "FNHMNHBQNV7L",
  "status": "NO_PLEA_RECEIVED_READY_FOR_DECISION",
  "listedInCriminalCourts": true
}
