=== hmcts/cpp-context-sjp/sjp-command/sjp-command-api/src/raml/json/schema/sjp.plead-online.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/sjp.plead-online-api.json",
  "type": "object",
  "properties": {
    "personalDetails": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "address": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/address.json"
        },
        "contactDetails": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/contact-details.json",
          "required": [
            "email"
          ]
        },
        "dateOfBirth": {
          "type": "string"
        },
        "nationalInsuranceNumber": {
          "type": "string"
        },
        "driverNumber": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/dvlaDriverLicence"
        },
        "driverLicenceDetails" : {
          "type" : "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "address",
        "contactDetails",
        "dateOfBirth"
      ],
      "additionalProperties": false
    },
    "legalEntityDefendant": {
      "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/plea/legal-entity-defendant.json",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/address.json"
        },
        "contactDetails": {
          "$ref":  "http://justice.gov.uk/json/schemas/domains/sjp/contact-details.json",
          "required": [
            "email"
          ]
        },
        "incorporationNumber": {
          "type": "string"
        },
        "position": {
          "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/plea/position.json",
          "type": "string",
          "enum": [
            "DIRECTOR",
            "SECRETARY",
            "SOLICITOR"
          ]
        }
      },
      "required": [
        "name",
        "address",
        "contactDetails"
      ],
      "additionalProperties": false
    },
    "offences": {
      "type": "array",
      "items": {
        "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/plea/offence.json",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "plea": {
            "type": "string",
            "enum": ["NOT_GUILTY", "GUILTY"]
          },

          "mitigation": {
            "type": "string"
          },
          "notGuiltyBecause": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "plea"
        ],
        "additionalProperties": false
      }
    },
    "comeToCourt": {
      "type": "boolean"
    },
    "witnessDispute": {
      "type": "string"
    },
    "witnessDetails": {
      "type": "string"
    },
    "outstandingFines": {
      "type": "boolean"
    },
    "interpreterLanguage": {
      "type": "string"
    },
    "speakWelsh": {
      "type": "boolean"
    },
    "unavailability": {
      "type": "string"
    },
    "financialMeans": {
      "type": "object",
      "properties": {
        "income": {
          "type": "object",
          "properties": {
            "amount": {
              "type": "number"
            },
            "frequency": {
              "type": "string",
              "enum": ["WEEKLY", "FORTNIGHTLY", "MONTHLY", "YEARLY"]
            }
          },
          "required": [
            "amount",
            "frequency"
          ],
          "additionalProperties": false
        },
        "benefits": {
          "type": "object",
          "properties": {
            "claimed": {
              "type": "boolean"
            },
            "type": {
              "type": "string"
            },
            "deductPenaltyPreference": {
              "type": "boolean"
            }
          },
          "required": [
            "claimed"
          ],
          "additionalProperties": false
        },
        "employmentStatus": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "legalEntityFinancialMeans": {
      "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/plea/legal-entity-financial-means.json",
      "type": "object",
      "properties": {
        "outstandingFines": {
          "type": "boolean"
        },
        "tradingMoreThan12Months": {
          "type": "boolean"
        },
        "numberOfEmployees": {
          "type": "integer"
        },
        "grossTurnover": {
          "type": "number"
        },
        "netTurnover": {
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "employer": {
      "type": "object",
      "properties": {
        "employeeReference": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "address": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/address.json"
        }
      },
      "required": [
        "name",
        "address"
      ],
      "additionalProperties": false
    },
    "outgoings": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "amount": {
            "type": "number"
          }
        },
        "additionalProperties": false
      }
    },
    "disabilityNeeds" : {
      "$ref": "http://cpp.moj.gov.uk/core/sjp/disability-needs.json"
    }
  },
  "anyOf": [
    {
      "required": [
        "personalDetails",
        "offences"
      ]
    },
    {
      "required": [
        "legalEntityDefendant",
        "offences"
      ]
    }
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-sjp/sjp-integration-test/src/test/resources/raml/json/sjp.command.plead-online__not-guilty_legal_entity.json
{
  "legalEntityFinancialMeans": {
      "outstandingFines": true,
      "tradingMoreThan12Months": true,
      "numberOfEmployees": 10,
      "grossTurnover": 10,
      "netTurnover": 10
    },
  "legalEntityDefendant": {
      "name": "test",
      "address": {
        "address1": "14 Tottenham Court Road",
        "address2": "London",
        "address3": "England",
        "address4": "UK",
        "address5": "Greater London",
        "postcode": "W1T 1JY"
      },
      "contactDetails": {
        "email": "criminal@gmail.com",
        "home": "02087654321"
      },
      "position": "DIRECTOR",
      "incorporationNumber": "C123232"
  },
  "offences": [
    {
      "id": "ecf30a03-8a17-4fc5-81d2-b72ac0a13d17",
      "plea": "NOT_GUILTY",
      "notGuiltyBecause": "I was forced to do it"
    }
  ],
  "witnessDispute": "They are lying",
  "witnessDetails": "My mate Dave",
  "interpreterLanguage": "French",
  "speakWelsh": false,
  "unavailability": "I'm on holiday November 17 to 19",
  "financialMeans": {
    "income": {
      "amount": 200.25,
      "frequency": "MONTHLY"
    },
    "benefits": {
      "claimed": true,
      "type": "jobseekers allowance",
      "deductPenaltyPreference": false
    },
    "employmentStatus": "my employment status"
  },
  "outgoings": [
    {
      "description": "Accommodation",
      "amount": 500.30
    },
    {
      "description": "Council Tax",
      "amount": 120.50
    },
    {
      "description": "Household bills",
      "amount": 50.80
    },
    {
      "description": "Travel expenses",
      "amount": 100.10
    },
    {
      "description": "Child maintenance",
      "amount": 500.20
    },
    {
      "description": "Other",
      "amount": 500.40
    }
  ]
}
