=== hmcts/cpp-context-sjp/sjp-event/sjp-event-listener/src/yaml/json/schema/sjp.events.defendant-accepted-aocp.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/event/defendant-accepted-aocp.json",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "personalDetails": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "address": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/address.json"
        },
        "contactDetails": {
          "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/contact-details.json",
          "required": [
            "email"
          ]
        },
        "dateOfBirth": {
          "type": "string"
        },
        "nationalInsuranceNumber": {
          "type": "string"
        },
        "driverNumber": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/dvlaDriverLicence"
        },
        "driverLicenceDetails" : {
          "type" : "string"
        },
        "region" : {
          "type" : "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "address",
        "contactDetails",
        "dateOfBirth"
      ],
      "additionalProperties": false
    },
    "offences": {
      "type": "array",
      "items": {
        "id": "http://justice.gov.uk/json/schemas/domains/sjp/command/offence.json",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "plea": {
            "type": "string",
            "enum": ["NOT_GUILTY", "GUILTY", "AOCP_PENDING"]
          },

          "mitigation": {
            "type": "string"
          },
          "notGuiltyBecause": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "plea"
        ],
        "additionalProperties": false
      }
    },
    "aocpAccepted" : {
      "type": "boolean"
    },
    "method": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/plea-method.json"
    },
    "mitigation": {
      "type": "string"
    },
    "pleadDate": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date-time"
    },
    "caseUrn" : {
      "type": "string"
    }
  },
  "required": [
    "caseId",
    "defendantId",
    "offences",
    "method",
    "pleadDate",
    "caseUrn"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-sjp/sjp-event/sjp-event-listener/src/yaml/json/sjp.events.defendant-accepted-aocp.json
{
  "caseId":"4076c764-a3b7-47b8-9d35-8fa706c1862a",
  "defendantId":"bdfd0bef-b459-4272-b286-fc6534d01e7a",
  "offences":[
    {
      "id":"c084b814-bcd5-444e-9044-ae0b5127ecd1",
      "plea":"AOCP_PENDING"
    }
  ],
  "method":"ONLINE",
  "personalDetails":{
    "firstName":"Testy",
    "lastName":"Testerson",
    "address":{
      "address1":"14 Tottenham Court Road",
      "address2":"London",
      "address3":"England",
      "address4":"UK",
      "address5":"Greater London",
      "postcode":"W1T 1JY"
    },
    "contactDetails":{
      "home":"0208000888",
      "mobile":"07890123123",
      "email":"criminal@gmail.com"
    },
    "dateOfBirth":"1990-09-09",
    "nationalInsuranceNumber":"AB123456A",
    "region":"croydon",
    "driverNumber":"TESTY708166G99KZ"
  },
  "aocpAccepted":true,
  "pleadDate":"2022-08-03T13:55:38.891Z",
  "caseUrn":"TFL766120493"
}
