=== hmcts/cpp-context-sjp/sjp-query/sjp-query-controller/src/raml/json/schema/sjp.query.case-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/queries/case-details.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "urn": {
      "type": "string"
    },
    "defendant": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/queries/defendant.json"
    },
    "dateTimeCreated": {
      "type": "string"
    },
    "caseDocuments": {
      "type": "array",
      "items": {
        "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/queries/document.json"
      }
    },
    "caseDecisions": {
      "type": "array",
      "items": {
        "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/queries/case-decision.json"
      }
    },
    "prosecutingAuthority": {
      "type" : "string"
    },
    "prosecutingAuthorityName": {
      "type" : "string"
    },
    "policeFlag": {
      "type": "boolean"
    },
    "postConviction": {
      "type": "boolean"
    },
    "completed": {
      "type": "boolean"
    },
    "assigned": {
      "type": "boolean"
    },
    "costs": {
      "type": "number"
    },
    "postingDate": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date"
    },
    "adjournedTo": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date"
    },
    "reopenedDate": {
      "type": "string"
    },
    "libraCaseNumber": {
      "type": "string"
    },
    "reopenedInLibraReason": {
      "type": "string"
    },
    "enterpriseId": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/enterprise-id.json"
    },
    "onlinePleaReceived": {
      "type" : "boolean"
    },
    "datesToAvoid": {
      "type" : "string"
    },
    "status": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/case-status.json"
    },
    "listedInCriminalCourts": {
      "type": "boolean"
    },
    "setAside": {
      "type": "boolean"
    },
    "managedByATCM": {
      "type": "boolean"
    },
    "caseApplication": {
      "$ref" : "http://justice.gov.uk/json/schemas/domains/sjp/case-application.json"
    }
  },
  "additionalProperties": true,
  "required": [
    "id",
    "urn"
  ]
}

=== hmcts/cpp-context-sjp/sjp-integration-test/src/test/resources/raml/json/sjp.command.plead-online__not-guilty_without_finances_case_response.json
{
  "urn": "${urn}",
  "prosecutingAuthority": "TFL",
  "costs": 1.23,
  "dateTimeCreated": "${dateTimeCreated}",
  "defendant": {
    "speakWelsh": false,
    "offences": [
      {
        "sequenceNumber": 1,
        "prosecutionFacts": "No ticket at the gates, forgery",
        "offenceCode": "PS00001",
        "cjsCode": "PS00001",
        "pendingWithdrawal": false,
        "hasFinalDecision": false,
        "pleaMethod": "ONLINE",
        "pleaDate": "${pleaDate}",
        "compensation": 2.34,
        "id": "${offenceId}",
        "plea": "NOT_GUILTY",
        "offenceSequenceNumber": 1,
        "wording": "Committed some offence",
        "chargeDate": "2016-01-01",
        "startDate": "2016-01-01",
        "title": "Postal service - convey a letter without a licence",
        "legislation": "Contrary to section 6(2) of the Postal Services Act 2000.",
        "notInEffect": true,
        "outOfTime": false,
        "imprisonable": true,
        "maxFineLevel": "S"
      }
    ],
    "caseId": "${caseId}",
    "numPreviousConvictions": 2,
    "personalDetails": {
      "firstName": "Testy",
      "lastName": "Testerson",
      "address": {
        "address1": "14 Tottenham Court Road",
        "address2": "London",
        "address3": "England",
        "address4": "UK",
        "address5": "Greater London",
        "postcode": "W1T 1JY"
      },
      "gender": "Male",
      "nationalInsuranceNumber": "AB123456A",
      "addressChanged": false,
      "dateOfBirth": "1990-09-09",
      "title": "Mr",
      "contactDetails": {
        "mobile": "07890123123",
        "email": "criminal@gmail.com",
        "home": "0208000888"
      },
      "dobChanged": true,
      "nameChanged": true
    },
    "interpreter": {
      "needed": true,
      "language": "French"
    },
    "id": "${defendantId}"
  },
  "caseDocuments": [
  ],
  "caseDecisions": [

  ],
  "listedInCriminalCourts": false,
  "assigned": false,
  "id": "${caseId}",
  "completed": false,
  "postingDate": "2015-12-02",
  "enterpriseId": "${enterpriseId}",
  "onlinePleaReceived": true,
  "status": "${caseStatus}"
}

=== hmcts/cpp-context-sjp/sjp-event/sjp-event-processor/src/test/resources/CaseCompletedProcessorTest/sjp.query.case-it.json
{
  "id": "0d61cb1c-d841-4262-9fd2-e726b8e4df35",
  "urn": "TVL6217620803",
  "defendant": {
    "id": "3371399b-a86b-43aa-85a9-f92e9a6b288b",
    "offences": [
      {
        "id": "86aa2966-fae7-4bd1-920a-52bb44c0293c",
        "offenceCode": "CA03011",
        "offenceSequenceNumber": 1,
        "wording": "On 10/08/2016 At thread needle street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without aConductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction",
        "wordingWelsh": "Prosecution charge wording in Welsh",
        "cjsCode": "CA03011",
        "sequenceNumber": 1,
        "startDate": "2020-12-30",
        "chargeDate": "2020-12-30",
        "backDuty": 340.3,
        "backDutyDateFrom": "2018-04-30",
        "backDutyDateTo": "2018-05-30",
        "compensation": 15.3,
        "prosecutionFacts": "Prosecution statements of facts",
        "endorsable": false,
        "pressRestrictable": false,
        "completed": true,
        "offenceDateCode": 1,
        "title": "Possess a    television set with intent to install / use without a licence",
        "legislation": "Contrary to section 363(3)(a) and (4) of the Communications Act 2003.",
        "outOfTime": false,
        "notInEffect": false,
        "imprisonable": false,
        "maxFineLevel": "3",
        "hasFinalDecision": true,
        "pendingWithdrawal": false,
        "backDutyOffence": false,
        "penaltyType": "",
        "sentencing": "",
        "titleWelsh": "Meddu ar set deledu gan fwriadu'i osod/ddefnyddio heb drwydded",
        "legislationWelsh": "Yn groes i adran 363(3)(a) a (4) Deddf Cyfathrebu 2003.",
        "maxFineValue": 1000
      },
      {
        "id": "9460d873-ff1c-469e-b189-a8b8743e1848",
        "offenceCode": "CA03013",
        "offenceSequenceNumber": 2,
        "wording": "On 10/08/2016 At thread needle street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without aConductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction",
        "wordingWelsh": "Prosecution charge wording in Welsh",
        "cjsCode": "CA03013",
        "sequenceNumber": 2,
        "startDate": "2020-12-30",
        "chargeDate": "2020-12-30",
        "backDuty": 340.3,
        "backDutyDateFrom": "2018-04-30",
        "backDutyDateTo": "2018-05-30",
        "compensation": 15.3,
        "prosecutionFacts": "Prosecution statements of facts",
        "withdrawalRequestReasonId": "93c6b978-4cad-31f0-a6d9-59cfd71c324a",
        "endorsable": false,
        "pressRestrictable": false,
        "completed": true,
        "offenceDateCode": 1,
        "title": "Obstruct    person executing search warrant for TV receiver",
        "legislation": "Contrary to section 366(8)(a) and    (9) of the Communications Act 2003.",
        "outOfTime": false,
        "notInEffect": false,
        "imprisonable": false,
        "maxFineLevel": "U",
        "hasFinalDecision": true,
        "pendingWithdrawal": false,
        "backDutyOffence": false,
        "penaltyType": "",
        "sentencing": "",
        "titleWelsh": "Rhwystro unigolyn a oedd yn gweithredu gwarant chwilio ar gyfer derbynnydd teledu",
        "legislationWelsh": "Yn groes i adran 366(8)(a) a (9) Deddf Cyfathrebu 2003.",
        "withdrawalRequestReason": "Agreement between prosecutor and defendant reached"
      }
    ],
    "caseId": "0d61cb1c-d841-4262-9fd2-e726b8e4df35",
    "interpreter": {
      "needed": false
    },
    "speakWelsh": false,
    "numPreviousConvictions": 3,
    "personalDetails": {
      "title": "Mr",
      "firstName": "John Adam Theodore",
      "lastName": "Protractor-6217620803",
      "dateOfBirth": "1980-02-04",
      "gender": "Not Specified",
      "nationalInsuranceNumber": "AA123456C",
      "driverNumber": "KER99861065SE9RP",
      "address": {
        "address1": "Flat 55",
        "address2": "1 Oxford Road",
        "address3": "'SW99 1AA'",
        "address4": "Surrey",
        "address5": "",
        "postcode": "SW99 1AA"
      },
      "contactDetails": {
        "email": "john@email.com"
      },
      "dobChanged": false,
      "addressChanged": false,
      "nameChanged": false
    },
    "disabilityNeeds": {
      "needed": false
    },
    "asn": "???"
  },
  "caseDecisions": [
    {
      "id": "e55daa5d-5bc5-4a5d-9cdc-140a5b1ea38f",
      "session": {
        "sessionId": "85571919-86bb-4d02-a495-e08cfea623ae",
        "legalAdviserUserId": "31ec3a16-8721-498c-8da5-f099390ee254",
        "courtHouseCode": "B23HS00",
        "courtHouseName": "Leamington Spa Magistrates' Court",
        "localJusticeAreaNationalCourtCode": "2905",
        "startedAt": "2021-01-29T09:14:53.607Z",
        "endedAt": "2021-01-29T09:15:02.464Z",
        "sessionType": "DELEGATED_POWERS",
        "legalAdviser": {
          "id": "31ec3a16-8721-498c-8da5-f099390ee254",
          "firstName": "Erica",
          "lastName": "Wilson"
        }
      },
      "savedAt": "2021-01-29T09:15:00.939Z",
      "offenceDecisions": [
        {
          "offenceId": "9460d873-ff1c-469e-b189-a8b8743e1848",
          "decisionType": "WITHDRAW",
          "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87",
          "verdict": "NO_VERDICT",
          "withdrawalReason": "Insufficient Evidence"
        }
      ]
    },
    {
      "id": "27354b44-e84e-4db8-b126-d7bb7ca4b036",
      "session": {
        "sessionId": "284eebcd-035d-4248-9724-a115308de640",
        "legalAdviserUserId": "31ec3a16-8721-498c-8da5-f099390ee254",
        "courtHouseCode": "B23HS00",
        "courtHouseName": "Leamington Spa Magistrates' Court",
        "localJusticeAreaNationalCourtCode": "2905",
        "magistrate": "Jenny",
        "startedAt": "2021-01-29T09:14:41.186Z",
        "endedAt": "2021-01-29T09:14:49.557Z",
        "sessionType": "MAGISTRATE",
        "legalAdviser": {
          "id": "31ec3a16-8721-498c-8da5-f099390ee254",
          "firstName": "Erica",
          "lastName": "Wilson"
        }
      },
      "savedAt": "2021-01-29T09:14:48.124Z",
      "offenceDecisions": [
        {
          "offenceId": "86aa2966-fae7-4bd1-920a-52bb44c0293c",
          "decisionType": "WITHDRAW",
          "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87",
          "verdict": "NO_VERDICT",
          "withdrawalReason": "Insufficient Evidence"
        },
        {
          "adjournedTo": "2021-02-05",
          "offenceId": "9460d873-ff1c-469e-b189-a8b8743e1848",
          "decisionType": "ADJOURN",
          "verdict": "NO_VERDICT"
        }
      ]
    }
  ],
  "dateTimeCreated": "2021-01-29T09:14:37.600Z",
  "caseDocuments": [
    {
      "id": "0a55f7be-349f-4204-bcc5-64b0638f1b30",
      "materialId": "4acb6610-386a-4efa-878b-b4a68e3f4d63",
      "documentType": "RESULT_ORDER",
      "documentNumber": 1,
      "addedAt": "2021-01-29T09:15:10.387Z"
    }
  ],
  "prosecutingAuthority": "TVL",
  "prosecutingAuthorityName": "TV Licensing",
  "completed": true,
  "assigned": false,
  "costs": 20.1,
  "postingDate": "2021-01-01",
  "enterpriseId": "G9667KW9V9SG",
  "onlinePleaReceived": false,
  "status": "COMPLETED",
  "listedInCriminalCourts": false,
  "policeFlag": false,
  "postConviction": false,
  "setAside": false
}

=== hmcts/cpp-context-sjp/sjp-integration-test/src/test/resources/raml/json/sjp.command.plead-online__guilty_with_driver_licence_details_case_response.json
{
  "urn": "${urn}",
  "prosecutingAuthority": "TFL",
  "policeFlag": false,
  "costs": 1.23,
  "postConviction": false,
  "dateTimeCreated": "${dateTimeCreated}",
  "prosecutingAuthorityName": "Transport for London",
  "defendant": {
    "offences": [
      {
        "sequenceNumber": 1,
        "prosecutionFacts": "No ticket at the gates, forgery",
        "offenceCode": "PS00001",
        "cjsCode": "PS00001",
        "pleaMethod": "ONLINE",
        "pendingWithdrawal": false,
        "hasFinalDecision": false,
        "pleaDate": "${pleaDate}",
        "compensation": 2.34,
        "id": "${offenceId}",
        "backDutyOffence": false,
        "penaltyType": "",
        "notInEffect": true,
        "sentencing": "",
        "maxFineLevel": "S",
        "plea": "GUILTY",
        "offenceSequenceNumber": 1,
        "wording": "Committed some offence",
        "chargeDate": "2016-01-01",
        "startDate": "2016-01-01",
        "title": "Postal service - convey a letter without a licence",
        "legislation": "Contrary to section 6(2) of the Postal Services Act 2000.",
        "backDuty": 340.3,
        "backDutyDateTo": "2015-05-30",
        "backDutyDateFrom": "2015-04-30",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "FG59 4FD",
        "outOfTime": false,
        "imprisonable": true,
        "endorsable": false
      }
    ],
    "caseId": "${caseId}",
    "numPreviousConvictions": 2,
    "personalDetails": {
      "driverNumber": "MORGA753116SM9IJ",
      "firstName": "Testy",
      "lastName": "Testerson",
      "address": {
        "address1": "14 Tottenham Court Road",
        "address2": "London",
        "address3": "England",
        "address4": "UK",
        "address5": "Greater London",
        "postcode": "W1T 1JY"
      },
      "gender": "Male",
      "nationalInsuranceNumber": "AB123456A",
      "dateOfBirth": "1990-09-09",
      "title": "Mr",
      "contactDetails": {
        "mobile": "07890123123",
        "email": "criminal@gmail.com",
        "home": "0208000888"
      },
      "dobChanged": true,
      "driverLicenceDetails": "Spanish driver Licence with number AAA896745",
      "addressChanged": false,
      "nameChanged": true
    },
    "interpreter": {
      "needed": false
    },
    "id": "${defendantId}",
    "speakWelsh": false
  },
  "caseDocuments": [
  ],
  "caseDecisions": [
  ],
  "listedInCriminalCourts": false,
  "postConviction": false,
  "assigned": false,
  "id": "${caseId}",
  "completed": false,
  "postingDate": "2015-12-02",
  "enterpriseId": "${enterpriseId}",
  "onlinePleaReceived": true,
  "status": "${caseStatus}"
}

=== hmcts/cpp-context-sjp/sjp-json/src/main/resources/json/example/queries/sjp.query.case.json
{
  "id": "5c019f8a-b3a3-40e5-9709-c54bc4f1c55c",
  "urn": "TFL75947ZQ8UE",
  "defendant": {
    "id": "c4d922ba-20c6-4d68-ab56-3611401bbc7c",
    "offences": [
      {
        "id": "72289b9e-5403-4e5b-8219-1d6ab004bbda",
        "offenceCode": "PS90010",
        "offenceSequenceNumber": 1,
        "wording": "On 02/07/2015 At Threadneedle Street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without a Conductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction ",
        "wordingWelsh": "Welsh wording: On 02/07/2015 At Threadneedle Street EC2 Being a passenger on a Public service Vehicle operated on behalf of London Bus Services Limited being used for the carriage of passengers at separate fares where the vehicle was being operated by a Driver without a Conductor did not as directed by the Driver an Inspector or a Notice displayed on the vehicle pay the fare for the journey in accordance with the direction ",
        "cjsCode": "PS90010",
        "sequenceNumber": 1,
        "startDate": "2017-12-29",
        "chargeDate": "2018-01-03",
        "compensation": 10,
        "prosecutionFacts": "An incident took place at GREEN PARK station whereby you were spoken to by a member of London Underground staff regarding your train journey and the associated fare.The facts of this incidents are now being considered and I must advise you that legal proceedings may be initiated against you regarding this matter in accordance with the LU prosecution policy",
        "backDuty": 340.30,
        "backDutyDateFrom": "2018-04-30",
        "backDutyDateTo": "2018-05-30",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "FG59 4FD",
        "backDutyOffence": true,
        "penaltyType": "Excise penalty",
        "sentencing": "Yes"
      }
    ],
    "caseId": "5c019f8a-b3a3-40e5-9709-c54bc4f1c55c",
    "interpreter": {
      "needed": false
    },
    "numPreviousConvictions": 2,
    "personalDetails": {
      "title": "Mr",
      "firstName": "John",
      "lastName": "Smith",
      "dateOfBirth": "1965-12-27",
      "gender": "Male",
      "address": {
        "address1": "Flat 1",
        "address2": " Armageddon House",
        "address3": "Giggleswick",
        "address4": "Merton",
        "address5": "Greater London",
        "postcode": "L32 1AB"
      },
      "contactDetails": {
        "home": "020 7219 5206",
        "mobile": "020 7219 5207",
        "email": "email@email.com"
      }
    }
  },
  "dateTimeCreated": "2018-02-02T12:51:58.742Z",
  "caseDocuments": [
    {
      "id": "7bde207f-ce57-49e5-b961-7577831171fb",
      "materialId": "7bde207f-ce57-49e5-b961-7577831171fb",
      "documentType": "SJPN",
      "documentNumber": 1,
      "addedAt": "2018-08-26T14:55:47.631Z"
    }
  ],
  "caseDecisions":[
    {
      "id":"32bcbaa6-ff56-40cb-8a71-408feb5077cc",
      "session":{
        "sessionId":"88dc450d-7d5c-4770-85fc-2c7126bc08c0",
        "legalAdviserUserId":"a085e359-6069-4694-8820-7810e7dfe762",
        "courtHouseCode":"B23HS00",
        "courtHouseName":"Leamington Spa Magistrates' Court",
        "localJusticeAreaNationalCourtCode":"2905",
        "magistrate":"re",
        "startedAt":"2019-06-04T14:34:54.164Z",
        "sessionType":"MAGISTRATE"
      },
      "savedAt":"2019-06-04T14:35:28.906Z"
    }
  ],
  "prosecutingAuthority": "TFL",
  "completed": false,
  "assigned": false,
  "costs": 20,
  "postingDate": "2018-01-05",
  "enterpriseId": "FNHMNHBQNV7L",
  "status": "NO_PLEA_RECEIVED_READY_FOR_DECISION",
  "listedInCriminalCourts": true
}
