=== hmcts/cpp-context-sjp/sjp-json/src/main/resources/json/schema/commands/defendant.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/json/schemas/domains/sjp/commands/defendant.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://cpp.moj.gov.uk/core/domain/json/schema/data-types.json#/definitions/uuid"
    },
    "title": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "dateOfBirth": {
      "type": "string"
    },
    "gender": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/gender.json"
    },
    "numPreviousConvictions": {
      "type": "integer"
    },
    "driverNumber": {
      "type": "string"
    },
    "languageNeeds": {
      "type": "string"
    },
    "nationalInsuranceNumber": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/national-insurance-number.json"
    },
    "address": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/address.json"
    },
    "contactDetails": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/contact-details.json"
    },
    "offences": {
      "type": "array",
      "items": {
        "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/commands/offence.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "address"
  ]
}

=== hmcts/cpp-context-sjp/sjp-json/src/main/resources/json/example/fragments/personal-details.json
{
  "title": "Mr",
  "firstName": "John",
  "lastName": "Smith",
  "dateOfBirth": "1965-12-27",
  "gender": "Male",
  "address": {
    "address1": "Flat 1",
    "address2": " Armageddon House",
    "address3": "Giggleswick",
    "address4": "Merton",
    "address5": "Greater London",
    "postcode": "L32 1AB"
  },
  "contactDetails": {
    "home": "020 7219 5206",
    "mobile": "020 7219 5207",
    "email": "email@email.com"
  }
}
